"""products table added

Revision ID: 37b04528e4cf
Revises: 1c36b72d9762
Create Date: 2023-02-11 11:25:05.009003

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '37b04528e4cf'
down_revision = '1c36b72d9762'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
