"""updating product model

Revision ID: b916e2b42bee
Revises: 3c39a7bd699d
Create Date: 2023-02-10 02:54:55.502998

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b916e2b42bee'
down_revision = '3c39a7bd699d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('image_url', sa.String(length=256), nullable=False))
    op.add_column('products', sa.Column('score', sa.Float(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'score')
    op.drop_column('products', 'image_url')
    # ### end Alembic commands ###
